#!/data/data/com.termux/files/usr/bin/bash

##Author : InYourHeart
##Team   : 2Easy4HackTeam

#colors
R='\033[1;31m'
B='\033[1;34m'
C='\033[0;36m'
G='\033[1;32m'
W='\033[1;37m'
Y='\033[1;33m'

DIR="$(pwd)"
date="$(date)"
time="$(date +%T)"
clear
echo
echo -e $B"----------------------"
echo -e $R"Author :$G InYourHeart"
echo -e $R"Team   :$C 2Easy4Hack"
echo -e $R"Tools  :$B SosmedTools"
echo -e $R"Version:$G V2.0"
echo -e $R"Date   :$Y 01/02/2019"
echo -e $R"Time   :$B 12.01.20 WIB"
echo -e $B"----------------------"
echo -e $R" [#] Editing this banner doesn't make you a programmer :)"
echo

echo
echo -e $Y"     Starting At $time "
echo -e $G" [*] Installing SosmedTools..."
sleep 1
if [ ! -d $HOME/.termux ]; then
mkdir $HOME/.termux
fi
echo -e $G" [*] Setting up program..."
echo -e $R" [*] Don't close the program!"
mv $DIR/sftools.zip $PREFIX/share
cd $PREFIX/share
sleep 3
echo
echo -e $G" Extracting Files..."
unzip stools.zip
unzip stools/igtools/node_modules.zip
chmod +x stools/2e4h
ln -s $PREFIX/share/stools/2e4h $PREFIX/bin/2e4h
echo - $G"  [*] Cleaning junk file..."
sleep 2
rm -f $PREFIX/share/stools.zip
rm -f $PREFIX/share/stools/igtools/node_modules.zip
sleep 2
echo
echo -e $G" [*] Setting up finished"
echo -e $G" [*] Now you can lauch the program just typing... ($B 2e4h $G)"
sleep 1
echo -e $G" [*] Enjoy this tools :) "
echo -e $G" [*] Support 2Easy4Hack Team "
sleep 1
echo -e $R" [*] Exiting the program... "
sleep 3
exit
